// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sexlwxvwfyrqmpioffxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNleGx3eHZ3ZnlycW1waW9mZnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjY3MDgsImV4cCI6MjA3MzM0MjcwOH0.W54NmkwL6P9TGqzGUVRv7RrJKCopDTANkWQ1fNQQVhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});